version: '3'

vars:
  DEVBOX_DIR_PATH: "$HOME/.local/share/devbox/global/default"

tasks:
  default:
    cmds:
      - task help
    silent: true

  help:
    cmds:
      - echo "Welcome to my project - maintainer<Tommy Tran Duc Thang> - email<tommytran.dev@gmail.com>"
      - echo "Run task <task_name> to run predefined script"
      - echo ""
      - echo "For setting up the environment            task local:install"
      - echo ""
      - task -l
    silent: true

  setup:
    desc: "install the environment, setup env for macOS and Ubuntu. To force update existing files run: task setup -- force"
    cmds:
      - echo "----------------------------------------------------------------"
      - echo "This requires sudo permission to run"
      - echo "Are you okay with it? This only uses the role to create symblink"
      - echo "----------------------------------------------------------------"
      - sudo echo "Starting to setup system"
      - echo "----------------------------------------------------------------"
      - which stow &> /dev/null || { echo "stow not installed, please install stow first"; exit 1; }
      - echo "Creating ~/.config directory if it doesn't exist..."
      - mkdir -p ~/.config
      - task: copydotfiles
      - command -v devbox &> /dev/null || { curl -fsSL https://get.jetify.com/devbox | bash; }
      - devbox global install 
    silent: true

  copydotfiles:
    desc: create symlink to dotfiles
    internal: true
    silent: true
    cmds: 
      - |
        # Stow all configuration folders to create symlinks in the home directory
        for dir in */; do
          dir=${dir%/} # Remove trailing slash
          if [ -d "$dir" ] && [ "$dir" != "node_modules" ] && [ "$dir" != ".git" ]; then
            echo "Creating symlinks for $dir"
            stow -R --target "$HOME" "$dir" 2>/dev/null || stow -R --target "$HOME" "$dir"
          fi
        done
